---
- name: Install Uchiwa dashboard
  apt:
    name: "uchiwa"
    state: present
    update_cache: yes
    cache_valid_time: 600
  tags:
    - monitoring
    - sensu
    - sensu-master

- name: Ensure the sensu configuration directory exists
  file:
    path: /etc/sensu/conf.d
    state: directory
  tags:
    - monitoring
    - sensu
    - sensu-master

- name: Add Sensu API configuration & checks
  copy:
    src: "{{ item }}"
    dest: /etc/sensu/conf.d/{{ item }}
    owner: root
    group: root
    mode: 0644
  with_items:
    - api.json
    - cpu_load_check.json
    - cpu_load_metrics.json
    - mem_percent_check.json
    - default_handler.json
    - disk_usage_check.json
  notify:
    - restart sensu-api
    - restart sensu-server
  tags:
    - monitoring
    - sensu
    - sensu-master

- name: Add sensu handlers configuration
  template:
    src: "{{ item }}"
    dest: "/etc/sensu/conf.d/{{ item | replace('json.j2', 'json') }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - logstash_handler.json.j2
    - victorops_handler.json.j2
  notify:
  - restart sensu-server
  - restart sensu-api
  tags:
    - monitoring
    - sensu
    - sensu-master

- name: Add Uchiwa configuration
  template:
    src: uchiwa.json.j2
    dest: /etc/sensu/uchiwa.json
    owner: root
    group: root
    mode: 0644
  notify:
    - restart uchiwa
  tags:
    - monitoring
    - sensu
    - sensu-master

- name: Ensure Uchiwa, sensu-api and sensu-server starts on boot
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - uchiwa
    - sensu-server
    - sensu-api
  tags:
    - monitoring
    - sensu
    - sensu-master

- name: Setup consul service and check definitions
  template:
    src: consul.json.j2
    dest: /etc/consul.d/sensu.json
    owner: root
    group: root
    mode: 0644
  notify:
    - restart consul
  tags:
    - monitoring
    - sensu
    - sensu-master
    - consul
