---

- name: remove GlusterFS PPA
  apt_repository:
    repo: "ppa:gluster/glusterfs-3.7"
    state: absent
  tags:
    - storage
    - gluster

- name: remove GlusterFS client
  apt:
    name: "glusterfs-client"
    state: absent
  tags:
    - storage
    - gluster

- name: Install NFS client
  apt:
    name: "nfs-common"
    state: present
  tags:
    - storage
    - efs

- name: Add docker deb repository keys
  apt_key:
    keyserver: p80.pool.sks-keyservers.net
    id: "58118E89F3A912897C070ADBF76221572C52609D"
  tags:
    - mesos
    - docker

- name: Remove (legacy) docker deb repository
  apt_repository:
    repo: "deb http://get.docker.io/ubuntu docker main"
    state: absent
  tags:
    - mesos
    - docker

- name: Add docker deb repository
  apt_repository:
    repo: "deb http://apt.dockerproject.org/repo ubuntu-trusty main"
    state: present
  tags:
    - mesos
    - docker

- name: Update repository cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - mesos
    - docker

- name: Remove legacy docker package
  apt:
    name: lxc-docker
    state: absent
    purge: yes
  tags:
    - mesos
    - docker

- name: Install docker engine
  apt:
    name: docker-engine
    state: present
  tags:
    - mesos
    - docker

- name: Install mesos
  apt:
    name: mesos
    state: present
  tags:
    - mesos

- name: Enable haproxy ppa
  apt_repository:
    repo: "ppa:vbernat/haproxy-1.6"
    state: present
  tags:
    - haproxy
    - consul-template

- name: Install haproxy
  apt:
    name: "haproxy"
    state: present
  tags:
    - haproxy
    - consul-template
