---
  - name: Get extra EC2 facts
    action: ec2_facts
    tags:
      - storage
      - efs

  - name: install ssh keys
    authorized_key:
      user: "{{ item.user }}"
      key: "{{ item.key }}"
    with_items:
      - { 'user':'ubuntu','key':'https://github.com/johngian.keys' }
      - { 'user':'ubuntu','key':'https://github.com/tannerfilip.keys' }
      - { 'user':'ubuntu','key':'https://github.com/flamingspaz.keys' }
      - { 'user':'ubuntu','key':'https://github.com/akatsoulas.keys' }

  - name: Add env var with AWS `env` tag value
    lineinfile:
      dest: /etc/environment
      regexp: '^AWS_ENV'
      line: 'AWS_ENV={{ ec2_tag_env }}'

  - name: Install common system packages
    apt:
      name: "{{ item }}"
    with_items:
      - emacs24-nox
      - tree
      - tcpdump
      - bsd-mailx
      - htop
      - sysstat
      - pv
      - nmap
      - netcat-openbsd
      - rsync
      - apticron
      - build-essential
      - ntp
      - apt-transport-https
      - python-boto
    tags:
      - common

  - name: Configure apticron
    template:
      src: apticron.conf.j2
      dest: /etc/apticron/apticron.conf
    tags:
      - monitoring
      - apticron

  - name: Add Sensu GPG key
    apt_key:
      url: "https://sensu.global.ssl.fastly.net/apt/pubkey.gpg"
      state: present
    tags:
      - monitoring
      - sensu
      - sensu-client
      - sensu-master

  - name: Add Sensu apt repo
    apt_repository:
      repo: "deb https://sensu.global.ssl.fastly.net/apt sensu main"
      state: present
    tags:
      - monitoring
      - sensu
      - sensu-client
      - sensu-master

  - name: Install Sensu
    apt:
      name: "sensu"
      state: present
      update_cache: yes
    tags:
      - monitoring
      - sensu
      - sensu-client
      - sensu-master

  - name: Ensure the sensu configuration directory exists
    file:
      path: /etc/sensu/conf.d
      state: directory
    tags:
      - monitoring
      - sensu
      - sensu-client
      - sensu-master

  - name: Add Sensu transport configuration
    copy:
      src: transport.json
      dest: /etc/sensu/conf.d/transport.json
      owner: root
      group: root
      mode: 0644
    notify:
      - restart sensu-client
    tags:
      - monitoring
      - sensu
      - sensu-client
      - sensu-master

  - name: Add Sensu Redis configuration
    template:
      src: redis.json.j2
      dest: /etc/sensu/conf.d/redis.json
      owner: root
      group: root
      mode: 0644
    notify:
      - restart sensu-client
    tags:
      - monitoring
      - sensu
      - sensu-client
      - sensu-master

  - name: Add Sensu client configuration
    template:
      src: client.json.j2
      dest: /etc/sensu/conf.d/client.json
      owner: root
      group: root
      mode: 0644
    notify:
      - restart sensu-client
    tags:
      - monitoring
      - sensu
      - sensu-client

  - name: Install sensu plugins
    gem:
      name: "{{ item }}"
      state: latest
      executable: /opt/sensu/embedded/bin/gem
      user_install: no
    with_items:
      - sensu-plugins-disk-checks
      - sensu-plugins-load-checks
      - sensu-plugins-memory-checks
      - sensu-plugins-consul
      - sensu-plugins-victorops
      - sensu-plugins-http
    tags:
      - monitoring
      - sensu-client

  - name: Ensure sensu-client starts on boot
    service:
      name: sensu-client
      enabled: yes
      state: started
    tags:
      - monitoring
      - sensu
      - sensu-client

  - name: Enable and start ntpd
    service:
      name: ntp
      enabled: yes
      state: started
    tags:
      - common
