---

- name: Install GlusterFS PPA
  apt_repository:
    repo: "ppa:gluster/glusterfs-3.7"
  tags:
    - gluster

- name: Install GlusterFS server
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - glusterfs-server
    - glusterfs-client
  tags:
    - gluster

- name: Ensure GlusterFS server is running
  service:
    name: glusterfs-server
    state: started
  tags:
    - gluster

- name: Ensure that `brick` directories exist
  file:
    path: "{{ brick_path}}/{{ item }}"
    state: directory
  with_items: gluster_volumes
  tags:
    - gluster

- name: Create replicated gluster volume
  gluster_volume:
    name: "{{ item }}"
    brick: "{{ brick_path}}/{{ item }}"
    replicas: "{{ groups['storage']|length }}"
    host: "{{ ansible_default_ipv4['address'] }}"
    cluster: "{% for host in groups['storage'] %}{{ hostvars[host].ansible_default_ipv4['address'] }}{% if not loop.last %},{% endif %}{% endfor %}"
    state: present
    force: yes
  when: inventory_hostname == "{{ groups['storage']|first }}"
  with_items: gluster_volumes
  tags:
    - gluster
